### ISSUE TITLE
Support generators?

### ISSUE THREAD

**Issue by binarykitchen** [oligot/rollup-plugin-nodent#1]
Would be great since buble doesn't support that yet and makes it hard for me to use with rollupjs in my branch.

**Comment by oligot** [comment]
nodent is not intended to transform generators code (only async/await).

While nodent can transform async/await to generators, it is [not recommended in the doc](https://github.com/MatAtBread/nodent#generators) as the performance is quite poor.

If you want to "polyfill" generators, you should have a look at [regenerator](http://facebook.github.io/regenerator/). There is even a [rollup plugin](https://github.com/noTruth/rollup-plugin-regenerator) (note that I haven't tested it).

**Comment by binarykitchen** [comment]
ah, cool, thanks for the links!
