### ISSUE TITLE
question: any limitation on sourcemaps handling?

### ISSUE THREAD

**Issue by xenogenesi** [oligot/rollup-plugin-nodent#5]
I'm using this plugin with gulp-better-rollup, rollup-plugin-vue and rollup-plugin-buble, when I enable it the result is one single concatenated `.js` as output with comments removed, and a `.map` file associated to this altered `.js` file.

When disabled I get (as expected) one `.js` and one `.map` but correctly mapping to a directory tree with the source files untouched, as shown in the chorme developer tools Sources tab (see images link below).

    gulp.task('js-main', function(cb) {
        pump([
            gulp.src('src/js/main.js'),
            ifElse(isProd, () => sourcemaps.init()),
            rollup({
                plugins: [
                    vue({
                        compileTemplate: true,
                        htmlMinifier: {
                            collapseWhitespace: false,
                            removeComments: false
                        },
                        css: destDir+'/css/bundle.css'}),
                    buble(),
                    nodent(/*{ sourcemap: true }*/),
                ]}, { format: 'iife' }),
            concat((isProd) ? 'main.min.js' : 'main.js'),
            ifElse(isProd, () => uglify()),
            ifElse(isProd, () => sourcemaps.write('')),
            gulp.dest(destDir+'/js'),
            browserSync.stream()
        ], cb);
    });

[right](https://s1.postimg.org/1me17hvbgf/right.png)
[wrong](https://s1.postimg.org/3sq77f8hb3/wrong.png)

Any idea why or how to solve?

**Comment by oligot** [comment]
Hi,

Can you create a small project that reproduces the bug so that I can try to understand what's the problem ?

**Comment by xenogenesi** [comment]
Hi, thanks for replying and for the plugin, [there](https://github.com/xenogenesi/test-nodent)

**Comment by oligot** [comment]
I just created [a PR on your project](https://github.com/xenogenesi/test-nodent/pull/1) that fixes the issue.
The trick is to set the option `sourceMap` to true (instead of `sourcemaps`).

Can you tell me if it works for you ?

**Comment by xenogenesi** [comment]
Dammit, yes it works, sorry about, thank you very much

**Comment by oligot** [comment]
No problem, glad it works for you.
