### ISSUE TITLE
It's choking when code contains JSX

### ISSUE THREAD

**Issue by shirotech** [oligot/rollup-plugin-nodent#7]
Hi there, nice plugin but it seems when we have both `async` and `jsx` code in out bundle it seems to have a "chicken and egg" problem.

```js
nodent({promises: true, noRuntime: true, es6target: true}),
buble({jsx: 'h', target: {ie: 10}}),
```
For instance if I put this `nodent` plugin before `buble`, here is what I am getting:
```
[!] (nodent plugin) SyntaxError: Unexpected token (22:4) /Users/van/Projects/ebex/compare-panel/index.js (nodent)
    <ComparePanel/>
```

```js
buble({jsx: 'h', target: {ie: 10}}),
nodent({promises: true, noRuntime: true, es6target: true}),
```

And when I have `buble` first:
```
[!] (nodent plugin) SyntaxError: Unexpected token (10:28) /Users/van/Projects/ebex/core/services/http.js (nodent)
HttpService.prototype.async getText = function getText (uri, type, params, headers) {
```

This problem does not exist if I remove either `JSX` or remove `async`.

**Comment by shirotech** [comment]
For those having the same problem, I found a temporary fix is to only include files that has `async` in it, if it has both `async` and `jsx` you will need to split them out.

Here is my working config:
```js
nodent({promises: true, noRuntime: true, es6target: true, include: /\/(?:cache|http)\.js$/}),
```

**Comment by oligot** [comment]
Hi,

There is a bit of configuration to make it work.
You can have a look at [these lines in microbundle](https://github.com/developit/microbundle/blob/e58b82b6816dde28e2402fffcec47c6958361818/src/index.js#L223-L244), or maybe directly use [microbundle](https://github.com/developit/microbundle) as it comes with nodent and buble built-in :smirk:

**Comment by shirotech** [comment]
Thanks @oligot works like a charm!
